Boilerplate: Update to 459c3cdf9d1bf451f99a08fbc21833c817d540e1
Conventions:
- openshift/golang-osd-operator: Update
---
https://github.com/openshift/boilerplate/compare/25bf1477435cc1d54ed1a0dff1c1f16405144db3...459c3cdf9d1bf451f99a08fbc21833c817d540e1

commit: 048e344dd49f9fb8070808b404721c75ddfd0f72
author: Manuel Dewald
Allow configuration of MAINPACKAGE and TESTTARGETS

* Consuming operators may want to have a different set of TESTTARGETS
* MAINPACKAGE differs for operator-sdk v1, allowing to override it will
  help onboarding operators on operator-sdk v1

commit: 60959312e1f456a47968bc8cc5839ee3435e6cdd
author: Eric Fried
golang-osd-operator: Cap concurrency for codecov

Some consumers were regularly having their coverage CI pods OOM-killed.
Experimenting with the prow configuration, we found we needed to set the
memory limits unreasonably high to make it work.

By default, cover tool runs with a number of threads equal to the
detected number of CPUs. In the CI environment at this time, that
appears to be 16. With this commit, we cap it at 4, which brings the
memory usage down to a manageable level without unduly affecting the
runtime of the job.

commit: b86c5e0dcd7a2f664a55236dc42de87658814d4c
author: Eric Fried
Update subscribers

The following have been onboarded and are marked as such:
- aws-account-operator
- aws-efs-operator
- managed-upgrade-operator

commit: 3dd1657739fe1ab4604f25bd5b777c8a66e9dd4c
author: Rafa Porres Molina
Add dry run mode to test to avoid pushes

Signed-off-by: Rafa Porres Molina <rporresm@redhat.com>

commit: ed0062e80fd0d826b303e87632eca0dba88f81ed
author: Rafa Porres Molina
Add missing push in git operations

This was left behind in the refactoring made in #104

Signed-off-by: Rafa Porres Molina <rporresm@redhat.com>

commit: dce934aab89c2a423ebc848c0621ecf1e6df52e6
author: Eric Fried
Improvements to container-make

- Run the container as self. Previously it was running as root, which
had some unintended consequences, including leaving root-owned files in
your repo.
- If the target fails, stay in the container so you can debug.
- Prints a usage statement if invoked with -h/--help.

diff --git a/boilerplate/_lib/container-make b/boilerplate/_lib/container-make
--- a/boilerplate/_lib/container-make
+++ b/boilerplate/_lib/container-make
@@ -1,10 +1,36 @@
 #!/bin/bash
 
+if [[ "$1" == "-h"* ]] || [[ "$1" == "--h"* ]]; then
+  echo "Usage: $0 {arguments to the real 'make'}"
+  echo "Runs 'make' in the boilerplate backing container."
+  echo "If the command fails, starts a shell in the container so you can debug."
+  exit -1
+fi
+
 source ${0%/*}/common.sh
 
 CONTAINER_ENGINE=$(command -v podman || command -v docker)
 [[ -n "$CONTAINER_ENGINE" ]] || err "Couldn't find a container engine. Are you already in a container?"
 
-# echo this regardless of BOILERPLATE_SET_X
-set -x
-$CONTAINER_ENGINE run --rm -v "$REPO_ROOT":"$REPO_ROOT" $IMAGE_PULL_PATH /bin/sh -c "cd $REPO_ROOT; make $@"
+# First set up a detached container with the repo mounted.
+banner "Starting the container"
+container_id=$($CONTAINER_ENGINE run -d -v "$REPO_ROOT":"$REPO_ROOT" $IMAGE_PULL_PATH tail -f /dev/null)
+if [[ $? -ne 0 ]] || [[ -z "$container_id" ]]; then
+  err "Couldn't start detached container"
+fi
+
+# Now run our `make` command in it with the right UID and working directory
+args="exec -it -u $(id -u):0 -w $REPO_ROOT $container_id"
+banner "Running: make $@"
+$CONTAINER_ENGINE $args make "$@"
+rc=$?
+
+# If it failed, drop into the container in a shell
+if [[ $rc -ne 0 ]]; then
+  banner "The 'make' command failed! Starting a shell in the container for debugging. Just 'exit' when done."
+  $CONTAINER_ENGINE $args /bin/bash
+fi
+
+# Finally, remove the container
+banner "Cleaning up the container"
+$CONTAINER_ENGINE rm -f $container_id >/dev/null
